#####
# Documentation
# Redwood: https://render.com/docs/deploy-redwood
# YAML (all config values): https://render.com/docs/yaml-spec
#####

services:
  - name: production-web
    type: web
    env: static
    buildCommand: cd redwood && yarn install --frozen-lockfile && yarn rw deploy render web
    staticPublishPath: ./redwood/web/dist
    envVars:
      - key: NODE_VERSION
        value: 16
    routes:
      - type: rewrite
        source: /.redwood/functions/*
        destination: https://zorro.xyz/*
      - type: rewrite
        source: /*
        destination: /index.html

  - name: production-api
    type: web
    env: node
    region: oregon
    buildCommand: cd redwood && yarn install --frozen-lockfile && yarn rw build api
    startCommand: cd redwood && yarn rw deploy render api
    envVars:
      - key: NODE_VERSION
        value: 16
      - key: DATABASE_URL
        fromDatabase:
          name: production-db
          property: connectionString

databases:
  - name: production-db
    region: oregon
