#####
# Documentation
# Redwood: https://render.com/docs/deploy-redwood
# YAML (all config values): https://render.com/docs/yaml-spec
#####

services:
  - name: redwood-web
    type: web
    env: static
    buildCommand: cd redwood && yarn install --frozen-lockfile &&  yarn rw deploy render web
    staticPublishPath: ./redwood/web/dist
    envVars:
      - key: NODE_VERSION
        value: 16
    routes:
      - type: rewrite
        source: /.redwood/functions/*
        #####
        # NOTE: replace destination api url after first deploy to Render
        # example:
        #   destination: https://myredwoodproject-api.onrender.com/*
        #####
        destination: replace_with_api_url/*
      - type: rewrite
        source: /*
        destination: /index.html

  - name: redwood-api
    type: web
    env: node
    region: oregon
    buildCommand: cd redwood && yarn && yarn rw build api
    startCommand: cd redwood && yarn rw deploy render api
    envVars:
      - key: NODE_VERSION
        value: 16
      - key: DATABASE_URL
        fromDatabase:
          name: redwood-db
          property: connectionString

databases:
  - name: redwood-db
    region: oregon
