[web]
  title = "Zorro"
  port = 8910
  apiUrl = "/.redwood/functions"

  # ENV vars that should be available to the web side
  includeEnvironmentVariables = [
    'CHAIN_DEPLOYMENT',
    'INFURA_IPFS_ID',
    'INFURA_IPFS_SECRET',
    'PUSHER_KEY',
    'PUSHER_CLUSTER'
  ]
[api]
  port = 8911
[browser]
  open = false
